"""Start the pinned vanilla server exactly as the frozen profile describes it.

The controlled test domain is a vanilla 1.21.4 dedicated server on loopback with
`online-mode=false`, and the profile fixture says so. This runs it: it verifies the
pinned jar, writes the settings the profile implies, starts the JVM, waits for the
server to report itself ready, and stops it again.

It exists because the server half of the controlled environment needs nothing but
Java, unlike the client half. What it does *not* do is accept the EULA on anyone's
behalf — that is the operator's to accept, so it must be asked for explicitly.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import signal
import subprocess
import sys
import time
from pathlib import Path
from typing import BinaryIO

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
PROFILE = (
    REPOSITORY_ROOT / "tests" / "fixtures" / "runtime-input" / "controlled-offline-server.json"
)
SERVER_SHA1 = "4707d00eb834b446575d89a61a11b5d548d8c001"
SERVER_SIZE = 56_880_250

# The world is fixed rather than random so that a run is reproducible, and flat so
# that generating it costs nothing on a machine that is not a runner.
FIXED_WORLD_SEED = "minekin-p0-controlled"
# A vanilla entity id: `minecraft:pig`, `pig`, and nothing that could be anything
# else. The command goes to the server's console, where a newline would be a
# second command, so the shape is checked rather than escaped.
_ENTITY_ID = re.compile(r"^[a-z0-9_.-]+(:[a-z0-9_./-]+)?$")
READY_MARKER = "Done ("
DEFAULT_READY_TIMEOUT_S = 240.0


def properties_for(profile: object, *, level_seed: str) -> dict[str, str]:
    """The server settings the frozen profile implies, and nothing it does not."""

    from minekin_core.adapters.launcher.server_profile import ServerProfile

    assert isinstance(profile, ServerProfile)
    return {
        "online-mode": "false" if profile.auth_mode == "offline" else "true",
        "server-ip": profile.host,
        "server-port": str(profile.port),
        "gamemode": "survival",
        "force-gamemode": "true",
        "difficulty": "normal",
        "hardcore": "false",
        "pvp": "true",
        "enable-rcon": "false",
        "enable-query": "false",
        "enable-status": "false",
        "enable-command-block": "false",
        "broadcast-console-to-ops": "false",
        "white-list": "true",
        "enforce-whitelist": "true",
        "spawn-protection": "0",
        "max-players": "2",
        "view-distance": "4",
        "simulation-distance": "4",
        "level-name": "world",
        "level-seed": level_seed,
        "level-type": "minecraft:flat",
        # Vanilla's default is 60, and it is wrong for this domain specifically:
        # a controlled server is empty for almost its whole life, because the
        # only player is one this launcher starts, and it is empty for exactly
        # the stretch in which that player is booting and connecting. Pausing is
        # a power saving for an idle production server, not for a domain whose
        # purpose is to be joined. (It did not turn out to be the cause of the
        # login failure that was being chased when this was added — that still
        # reproduces with pausing off — so it is a fix for a real wrongness
        # rather than for that symptom.)
        "pause-when-empty-seconds": "0",
        "motd": f"Minekin controlled offline test domain ({profile.profile_id})",
    }


def write_configuration(
    directory: Path,
    properties: dict[str, str],
    *,
    allowed_players: tuple[str, ...],
) -> None:
    """Create one fresh server run; never overwrite evidence from an older run."""

    from minekin_core.domain.offline_identity import is_valid_username, offline_player_uuid

    invalid = sorted({name for name in allowed_players if not is_valid_username(name)})
    if invalid:
        raise SystemExit("invalid vanilla player name(s): " + ", ".join(invalid))
    unique_players: dict[str, str] = {}
    for name in allowed_players:
        folded = name.casefold()
        prior = unique_players.get(folded)
        if prior is not None and prior != name:
            raise SystemExit(f"player names differ only by case: {prior}, {name}")
        unique_players[folded] = name
    if directory.exists() and any(directory.iterdir()):
        raise SystemExit(f"{directory} is not empty; use a fresh run directory")
    directory.mkdir(parents=True, exist_ok=True)

    lines = ["# Generated by tools/run_controlled_server.py from the frozen profile."]
    lines.extend(f"{key}={value}" for key, value in sorted(properties.items()))
    (directory / "server.properties").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (directory / "eula.txt").write_text(
        "# Accepted by the operator via --accept-eula.\neula=true\n", encoding="utf-8"
    )
    whitelist = [
        {"uuid": str(offline_player_uuid(name)), "name": name}
        for name in sorted(unique_players.values(), key=str.casefold)
    ]
    (directory / "whitelist.json").write_text(
        json.dumps(whitelist, indent=2) + "\n", encoding="utf-8"
    )
    (directory / "ops.json").write_text("[]\n", encoding="utf-8")


def summon_command(entity_type: str) -> str:
    """The console line that puts one entity at the world spawn, or a refusal.

    The controlled world is empty and flat, so without this the first snapshot's
    visible world is vacuously empty and the entity path is never exercised by a
    run. It is a console command, which is a channel where an unchecked string is
    a second command, so the entity id is matched against the shape vanilla
    ids have rather than escaped.
    """

    if not _ENTITY_ID.fullmatch(entity_type):
        raise SystemExit(f"not a vanilla entity id: {entity_type!r}")
    return f"summon {entity_type} ~ ~ ~"


def kill_command(player: str) -> str:
    """The console line that kills a player, or a refusal.

    The one release trigger a server can cause is a death: the client shows its
    death screen, the keyboard stops belonging to the world, and the Bridge is
    the only side that can see it. So a run that wants to exercise that has to
    be able to kill the Kin, and only the server can.

    A console command like the others, so the name is checked rather than
    escaped.
    """

    from minekin_core.domain.offline_identity import is_valid_username

    if not is_valid_username(player):
        raise SystemExit(f"not a vanilla player name: {player!r}")
    return f"kill {player}"


def has_joined(log: Path, player: str) -> bool:
    """Whether the server has said this player is in the world."""

    try:
        text = log.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return False
    return f"{player} joined the game" in text


def request_clean_stop(signum: int, frame: object) -> None:
    """Route a stop signal into the same path Ctrl+C already takes.

    Handled explicitly rather than left to the default, because the default is
    not the same disposition in every process that runs this tool. A background
    job of a non-interactive shell — which is how the domain runner starts it —
    inherits SIGINT set to *ignore*, so the SIGINT that runner sent was a no-op
    and the server it should have stopped kept running until the container was
    killed. SIGTERM's default is the opposite failure: it dies at once, without
    reaching the `stop` that saves the world. Measured in the runner image:
    `SIGINT SIG_IGN`, `SIGTERM SIG_DFL`, and `kill -INT` on such a process
    leaves it alive.

    Both are now the clean stop, and both are installed even where the inherited
    disposition was to ignore, so a caller does not have to know which kind of
    process it started.
    """

    raise KeyboardInterrupt


def position_probe_command(player: str) -> str:
    """The console line that makes the server say where a player is.

    The acceptance for input is that the *server* observes the displacement, and
    a server does not log where anyone walks. Asking it is the only way to get
    its own answer: the reply goes to the console, which is where this runs.

    Like the summon, it is a console command, so the name is checked against the
    shape a vanilla player name has rather than escaped.
    """

    from minekin_core.domain.offline_identity import is_valid_username

    if not is_valid_username(player):
        raise SystemExit(f"not a vanilla player name: {player!r}")
    return f"data get entity {player} Pos"


def _sha1(stream: BinaryIO) -> str:
    digest = hashlib.sha1(usedforsecurity=False)
    while chunk := stream.read(1024 * 1024):
        digest.update(chunk)
    return digest.hexdigest()


def verify_jar(path: Path) -> None:
    if not path.is_file():
        raise SystemExit(f"{path} is missing; download the pinned server jar first")
    if path.stat().st_size != SERVER_SIZE:
        raise SystemExit("the server jar is not the pinned artifact")
    with path.open("rb") as stream:
        digest = _sha1(stream)
    if digest != SERVER_SHA1:
        raise SystemExit("the server jar is not the pinned artifact")


def wait_for_ready(log: Path, process: subprocess.Popen[bytes], timeout_s: float) -> bool:
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        if log.is_file() and READY_MARKER in log.read_text(encoding="utf-8", errors="replace"):
            return True
        if process.poll() is not None:
            return False
        time.sleep(0.5)
    return False


def stop(process: subprocess.Popen[bytes], *, timeout_s: float = 60.0) -> None:
    """Ask the server to save and exit, then insist if it does not."""

    if process.poll() is not None:
        return
    if process.stdin is not None:
        try:
            process.stdin.write(b"stop\n")
            process.stdin.flush()
        except (OSError, ValueError):
            pass
    try:
        process.wait(timeout=timeout_s)
    except subprocess.TimeoutExpired:
        process.terminate()
        try:
            process.wait(timeout=timeout_s)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--directory", type=Path, required=True)
    parser.add_argument("--jar", type=Path, required=True)
    parser.add_argument("--accept-eula", action="store_true")
    parser.add_argument("--ready-timeout", type=float, default=DEFAULT_READY_TIMEOUT_S)
    parser.add_argument("--keep-running", action="store_true")
    parser.add_argument(
        "--summon",
        default=None,
        metavar="ENTITY_TYPE",
        help="put one entity at the world spawn, so the world is not empty",
    )
    parser.add_argument("--java", type=Path, default=None)
    parser.add_argument(
        "--kill-player",
        default=None,
        metavar="NAME",
        help="kill this player once it has joined, so a release has a cause",
    )
    parser.add_argument(
        "--kill-after-join-seconds",
        type=float,
        default=6.0,
        help="how long after the join to kill it (default 6)",
    )
    parser.add_argument(
        "--probe-player",
        default=None,
        metavar="NAME",
        help="make the server report this player's position, so a run can show movement",
    )
    parser.add_argument(
        "--probe-every-seconds",
        type=float,
        default=5.0,
        help="how often the position probe is asked (default 5)",
    )
    parser.add_argument(
        "--allow-player",
        action="append",
        default=[],
        help="offline player name to put in whitelist.json; may be repeated",
    )
    args = parser.parse_args()

    if not args.accept_eula:
        print(
            "the Minecraft EULA must be accepted by the operator: pass --accept-eula",
            file=sys.stderr,
        )
        return 2
    if args.ready_timeout <= 0:
        print("--ready-timeout must be positive", file=sys.stderr)
        return 2
    if args.probe_every_seconds <= 0:
        print("--probe-every-seconds must be positive", file=sys.stderr)
        return 2
    if args.kill_after_join_seconds <= 0:
        print("--kill-after-join-seconds must be positive", file=sys.stderr)
        return 2

    for stop_signal in (signal.SIGINT, signal.SIGTERM):
        signal.signal(stop_signal, request_clean_stop)

    from minekin_core.adapters.launcher.server_profile import load_server_profile
    from minekin_core.config import java_executable

    profile = load_server_profile(PROFILE)
    properties = properties_for(profile, level_seed=FIXED_WORLD_SEED)
    verify_jar(args.jar)
    write_configuration(
        args.directory,
        properties,
        allowed_players=tuple(args.allow_player),
    )

    summon = None if args.summon is None else summon_command(args.summon)
    probe = None if args.probe_player is None else position_probe_command(args.probe_player)
    kill = None if args.kill_player is None else kill_command(args.kill_player)
    joined_at = None
    # Asked immediately: the join line the server already writes says where the
    # player started, and a probe that waited a full interval would only say it
    # again.
    next_probe = 0.0
    java = args.java or java_executable()
    log = args.directory / "server.log"
    with log.open("wb") as stream:
        process = subprocess.Popen(
            [str(java), "-Xms512M", "-Xmx1024M", "-jar", str(args.jar), "nogui"],
            cwd=str(args.directory),
            stdin=subprocess.PIPE,
            stdout=stream,
            stderr=subprocess.STDOUT,
        )
        print(f"started {process.pid}; waiting for {READY_MARKER!r} in {log}")
        try:
            ready = wait_for_ready(log, process, args.ready_timeout)
            if not ready:
                tail = log.read_text(encoding="utf-8", errors="replace").splitlines()[-20:]
                print("\n".join(tail), file=sys.stderr)
                return 1
            if summon is not None and process.stdin is not None:
                # After ready and before anything connects: the entity has to
                # exist by the time a client takes its first snapshot.
                process.stdin.write((summon + "\n").encode())
                process.stdin.flush()
                print(f"summoned: {args.summon}")
            if args.keep_running:
                print("server is up; press Ctrl+C to stop it cleanly")
                while process.poll() is None:
                    if (
                        probe is not None
                        and process.stdin is not None
                        and time.monotonic() >= next_probe
                    ):
                        # Written to the console, so the server's own log holds
                        # where the player was and when. A run that moved the Kin
                        # is one the server can be asked about; nothing else in
                        # the run can answer for it.
                        process.stdin.write((probe + "\n").encode())
                        process.stdin.flush()
                        next_probe = time.monotonic() + args.probe_every_seconds
                    # Killed through a death rather than a disconnect: a disconnect
                    # ends the session, and a death is the case where the client is
                    # still running and no longer taking input.
                    if kill is not None and process.stdin is not None:
                        if joined_at is None and has_joined(log, str(args.kill_player)):
                            joined_at = time.monotonic()
                        if (
                            joined_at is not None
                            and time.monotonic() - joined_at >= args.kill_after_join_seconds
                        ):
                            process.stdin.write((kill + "\n").encode())
                            process.stdin.flush()
                            print(f"killed: {args.kill_player}")
                            kill = None
                    time.sleep(0.1)
                return process.returncode
        finally:
            stop(process)

    print(f"Controlled server: OK (ready, then stopped; {log} holds the run)")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except KeyboardInterrupt:
        # Only reachable outside the `--keep-running` wait: a stop signal that
        # arrives while the server is merely being started. The world is already
        # saved by the `finally` above, so this is the exit code, not a rescue.
        print("stopped by signal", file=sys.stderr)
        raise SystemExit(130) from None
