"""Start the pinned vanilla server exactly as the frozen profile describes it.

The controlled test domain is a vanilla 1.21.4 dedicated server on loopback with
`online-mode=false`, and the profile fixture says so. This runs it: it verifies the
pinned jar, writes the settings the profile implies, starts the JVM, waits for the
server to report itself ready, and stops it again.

It exists because the server half of the controlled environment needs nothing but
Java, unlike the client half. What it does *not* do is accept the EULA on anyone's
behalf — that is the operator's to accept, so it must be asked for explicitly.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
import time
from pathlib import Path
from typing import BinaryIO

REPOSITORY_ROOT = Path(__file__).resolve().parents[1]
PROFILE = (
    REPOSITORY_ROOT / "tests" / "fixtures" / "runtime-input" / "controlled-offline-server.json"
)
SERVER_SHA1 = "4707d00eb834b446575d89a61a11b5d548d8c001"
SERVER_SIZE = 56_880_250

# The world is fixed rather than random so that a run is reproducible, and flat so
# that generating it costs nothing on a machine that is not a runner.
FIXED_WORLD_SEED = "minekin-p0-controlled"
READY_MARKER = "Done ("
DEFAULT_READY_TIMEOUT_S = 240.0


def properties_for(profile: object, *, level_seed: str) -> dict[str, str]:
    """The server settings the frozen profile implies, and nothing it does not."""

    from minekin_core.adapters.launcher.server_profile import ServerProfile

    assert isinstance(profile, ServerProfile)
    return {
        "online-mode": "false" if profile.auth_mode == "offline" else "true",
        "server-ip": profile.host,
        "server-port": str(profile.port),
        "gamemode": "survival",
        "force-gamemode": "true",
        "difficulty": "normal",
        "hardcore": "false",
        "pvp": "true",
        "enable-rcon": "false",
        "enable-query": "false",
        "enable-status": "false",
        "enable-command-block": "false",
        "broadcast-console-to-ops": "false",
        "white-list": "true",
        "enforce-whitelist": "true",
        "spawn-protection": "0",
        "max-players": "2",
        "view-distance": "4",
        "simulation-distance": "4",
        "level-name": "world",
        "level-seed": level_seed,
        "level-type": "minecraft:flat",
        # Vanilla's default is 60, and it is wrong for this domain specifically:
        # a controlled server is empty for almost its whole life, because the
        # only player is one this launcher starts, and it is empty for exactly
        # the stretch in which that player is booting and connecting. Pausing is
        # a power saving for an idle production server, not for a domain whose
        # purpose is to be joined. (It did not turn out to be the cause of the
        # login failure that was being chased when this was added — that still
        # reproduces with pausing off — so it is a fix for a real wrongness
        # rather than for that symptom.)
        "pause-when-empty-seconds": "0",
        "motd": f"Minekin controlled offline test domain ({profile.profile_id})",
    }


def write_configuration(
    directory: Path,
    properties: dict[str, str],
    *,
    allowed_players: tuple[str, ...],
) -> None:
    """Create one fresh server run; never overwrite evidence from an older run."""

    from minekin_core.domain.offline_identity import is_valid_username, offline_player_uuid

    invalid = sorted({name for name in allowed_players if not is_valid_username(name)})
    if invalid:
        raise SystemExit("invalid vanilla player name(s): " + ", ".join(invalid))
    unique_players: dict[str, str] = {}
    for name in allowed_players:
        folded = name.casefold()
        prior = unique_players.get(folded)
        if prior is not None and prior != name:
            raise SystemExit(f"player names differ only by case: {prior}, {name}")
        unique_players[folded] = name
    if directory.exists() and any(directory.iterdir()):
        raise SystemExit(f"{directory} is not empty; use a fresh run directory")
    directory.mkdir(parents=True, exist_ok=True)

    lines = ["# Generated by tools/run_controlled_server.py from the frozen profile."]
    lines.extend(f"{key}={value}" for key, value in sorted(properties.items()))
    (directory / "server.properties").write_text("\n".join(lines) + "\n", encoding="utf-8")
    (directory / "eula.txt").write_text(
        "# Accepted by the operator via --accept-eula.\neula=true\n", encoding="utf-8"
    )
    whitelist = [
        {"uuid": str(offline_player_uuid(name)), "name": name}
        for name in sorted(unique_players.values(), key=str.casefold)
    ]
    (directory / "whitelist.json").write_text(
        json.dumps(whitelist, indent=2) + "\n", encoding="utf-8"
    )
    (directory / "ops.json").write_text("[]\n", encoding="utf-8")


def _sha1(stream: BinaryIO) -> str:
    digest = hashlib.sha1(usedforsecurity=False)
    while chunk := stream.read(1024 * 1024):
        digest.update(chunk)
    return digest.hexdigest()


def verify_jar(path: Path) -> None:
    if not path.is_file():
        raise SystemExit(f"{path} is missing; download the pinned server jar first")
    if path.stat().st_size != SERVER_SIZE:
        raise SystemExit("the server jar is not the pinned artifact")
    with path.open("rb") as stream:
        digest = _sha1(stream)
    if digest != SERVER_SHA1:
        raise SystemExit("the server jar is not the pinned artifact")


def wait_for_ready(log: Path, process: subprocess.Popen[bytes], timeout_s: float) -> bool:
    deadline = time.monotonic() + timeout_s
    while time.monotonic() < deadline:
        if log.is_file() and READY_MARKER in log.read_text(encoding="utf-8", errors="replace"):
            return True
        if process.poll() is not None:
            return False
        time.sleep(0.5)
    return False


def stop(process: subprocess.Popen[bytes], *, timeout_s: float = 60.0) -> None:
    """Ask the server to save and exit, then insist if it does not."""

    if process.poll() is not None:
        return
    if process.stdin is not None:
        try:
            process.stdin.write(b"stop\n")
            process.stdin.flush()
        except (OSError, ValueError):
            pass
    try:
        process.wait(timeout=timeout_s)
    except subprocess.TimeoutExpired:
        process.terminate()
        try:
            process.wait(timeout=timeout_s)
        except subprocess.TimeoutExpired:
            process.kill()
            process.wait()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--directory", type=Path, required=True)
    parser.add_argument("--jar", type=Path, required=True)
    parser.add_argument("--accept-eula", action="store_true")
    parser.add_argument("--ready-timeout", type=float, default=DEFAULT_READY_TIMEOUT_S)
    parser.add_argument("--keep-running", action="store_true")
    parser.add_argument("--java", type=Path, default=None)
    parser.add_argument(
        "--allow-player",
        action="append",
        default=[],
        help="offline player name to put in whitelist.json; may be repeated",
    )
    args = parser.parse_args()

    if not args.accept_eula:
        print(
            "the Minecraft EULA must be accepted by the operator: pass --accept-eula",
            file=sys.stderr,
        )
        return 2
    if args.ready_timeout <= 0:
        print("--ready-timeout must be positive", file=sys.stderr)
        return 2

    from minekin_core.adapters.launcher.server_profile import load_server_profile
    from minekin_core.config import java_executable

    profile = load_server_profile(PROFILE)
    properties = properties_for(profile, level_seed=FIXED_WORLD_SEED)
    verify_jar(args.jar)
    write_configuration(
        args.directory,
        properties,
        allowed_players=tuple(args.allow_player),
    )

    java = args.java or java_executable()
    log = args.directory / "server.log"
    with log.open("wb") as stream:
        process = subprocess.Popen(
            [str(java), "-Xms512M", "-Xmx1024M", "-jar", str(args.jar), "nogui"],
            cwd=str(args.directory),
            stdin=subprocess.PIPE,
            stdout=stream,
            stderr=subprocess.STDOUT,
        )
        print(f"started {process.pid}; waiting for {READY_MARKER!r} in {log}")
        try:
            ready = wait_for_ready(log, process, args.ready_timeout)
            if not ready:
                tail = log.read_text(encoding="utf-8", errors="replace").splitlines()[-20:]
                print("\n".join(tail), file=sys.stderr)
                return 1
            if args.keep_running:
                print("server is up; press Ctrl+C to stop it cleanly")
                try:
                    process.wait()
                except KeyboardInterrupt:
                    return 130
                return process.returncode
        finally:
            stop(process)

    print(f"Controlled server: OK (ready, then stopped; {log} holds the run)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
